name: Execução parodify com Library Browser
run-name: On Push - parodify Browser
on: [push]

jobs:
    web-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Install Python 
              uses: actions/setup-python@v4
              with:
                python-version: '3.12.2'

            - name: Install Node.js 
              uses: actions/setup-node@v4
              with:
                node-version: '20.12.0'

            - name: Install Requirements
              run: |
                python -m pip install --upgrade pip
                pip install -U -r requirements.txt
                sudo npm install @playwright/test
                sudo npx playwright install-deps
                rfbrowser init

            - name: Execução dos testes
              run: |
                robot -v HEADLESS:true cenarios/